version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080" 
    restart: always
    command: ["npm", "run", "docker:start"]
    environment:
      - TZ=America/Sao_Paulo
      - MONGO_URL=mongodb://mongodb:27017/culttivo
      - PORTA=8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
